[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/unite-outline'

# ペースト
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# File System
[[plugins]]
repo = 'Shougo/vimfiler'

# Shell
[[plugins]]
repo = 'Shougo/vimproc'
[[plugins]]
repo = 'Shougo/vimshell'

# 括弧
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'luochen1990/rainbow'

# 画面分割の時に使うもの
[[plugins]]
repo = 'kana/vim-submode'

# 文字の入れ替え
[[plugins]]
repo = 'kana/vim-operator-replace'
[[plugins]]
repo = 'kana/vim-operator-user'

# MD 記法
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'previm/previm'

# QuickRun
[[plugins]]
repo = 'thinca/vim-quickrun'

# Copilot
[[plugins]]
repo = 'github/copilot.vim'
