
# 補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/unite-outline'

# ペースト
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# File System
[[plugins]]
repo = 'Shougo/vimfiler'

# Shell
[[plugins]]
repo = 'Shougo/vimproc'
[[plugins]]
repo = 'Shougo/vimshell'

# 括弧
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'luochen1990/rainbow'

# csv
[[plugins]]
repo = 'mechatroner/rainbow_csv'

# 画面分割の時に使うもの
[[plugins]]
repo = 'kana/vim-submode'

# 文字の入れ替え
[[plugins]]
repo = 'kana/vim-operator-replace'
[[plugins]]
repo = 'kana/vim-operator-user'

# MD 記法
[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
repo = 'iamcco/markdown-preview.vim'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'previm/previm'

# QuickRun
[[plugins]]
repo = 'thinca/vim-quickrun'

# Javascript
[[plugins]]
repo = 'leafgarland/typescript-vim'

# QML
[[plugins]]
repo = 'peterhoeg/vim-qml'

# vue
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'zigford/vim-powershell'

 # Rust lang
[[plugins]]
repo = 'racer-rust/vim-racer'
[[plugins]]
repo = 'rust-lang/rust.vim'
[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']

# mql4
[[plugins]]
repo = 'vobornik/vim-mql4'

# elm
[[plugins]]
repo = 'lambdatoast/elm.vim'

# C++
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'

# web template
[[plugins]]
repo = 'statianzo/vim-jade'
[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

# latex
[[plugins]]
repo = 'lervag/vimtex'

# Flutter
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

# toml
[[plugins]]
repo = 'cespare/vim-toml'

